### ISSUE TITLE
SSR Issues

### ISSUE THREAD

**Issue by syropian** [cloudinary/cloudinary-vue#62] opened 2020-02-26 04:39 UTC
I'm trying to use cloudinary-vue with a Nuxt application, but I'm getting an SSR warning from Nuxt everywhere I server render a `CldImage` component. It mentions that theres mismatching childNodes vs. VNodes, and there appears to be extra an text node in the VNode list. I've attached a screenshot from my browser console:

![Screen Shot 2020-02-25 at 11 37 31 PM](https://user-images.githubusercontent.com/749061/75312433-e2303380-5827-11ea-9990-0d7d7182b18f.png)

**Comment by joshukraine** [comment] 2020-02-27 13:41
I have experienced this same issue on my blog, which is built with Nuxt. Here is one of my image components: https://github.com/joshukraine/ofreport.com/blob/master/components/ArticleImage.vue Full repo is open source.

**Comment by mayashavin** [comment] 2020-03-03 15:05
@syropian I saw you are using `"cloudinary-vue": "^1.0.0-beta3"`. Please change it to `^1.0.0` as we solved this problem in SSR with the official version 1.0.0. The beta3 version doesn't work directly with SSR and will need to use a workaround.
Let me know if you need other help.

**Comment by syropian** [comment] 2020-03-03 22:03
@mayashavin I have `"cloudinary-vue": "^1.0.0",` in my package.json file already, and I confirmed it's `"version": "1.0.0",` by looking in `node_modules`.

**Comment by joshukraine** [comment] 2020-03-04 04:29
@mayashavin Thank you for the information. I was also on `"cloudinary-vue": "^1.0.0-beta3"`, but I have just now updated to v1.0.0, and I can confirm that the issue persists. During normal client-side navigation, the pages render without errors. But if I refresh the page (SSR), I get the usual errors about mismatches in the virtual DOM. (See PR link above, screenshot below.)

<img width="591" alt="Screenshot 2020-03-04 06 21 28" src="https://user-images.githubusercontent.com/615841/75845333-6f075e00-5de1-11ea-91c7-2a09518f89fa.png">

**Comment by pktharindu** [comment] 2020-07-04 13:48
Wrapping it with a `client-only` tag works for me.

```html
<client-only>
  <cld-image
    public-id=""
    quality="auto"
    responsive="auto"
    fetch-format="auto"
  />
</client-only>
```

**Comment by unr** [comment] 2020-11-05 21:30
It sounds like this is an ongoing issue?

If the expectation is that every image using CldImage is to be client only, will likely just have to go back to using straight urls. Not useful in an SSR Nuxt Application.

**Comment by mayashavin** [comment] 2020-11-09 11:25
`responsive` is a client-only tag, since it calculates the size base on the actual viewport. 

If you don't use `responsive`, CldImage should work normally regardless server or client. However, the new version of Cloudinary-Vue SDK will address the issue of mis-matching content render.

@unr @joshukraine

**Comment by mayashavin** [comment] 2020-11-23 09:03
fixed in #117

**Closed by mayashavin** 2020-11-23 09:03 UTC
Labels: bug

**Comment by finex** [comment] 2021-04-09 12:54
> `responsive` is a client-only tag, since it calculates the size base on the actual viewport.
> 
> If you don't use `responsive`, CldImage should work normally regardless server or client. However, the new version of Cloudinary-Vue SDK will address the issue of mis-matching content render in general.
> 
> @unr @joshukraine

Hi, I'm currently using the latest nuxt.js cloudinary plugin (1.25.1) with cloudinary-vue 1.2.0 and when I generate the website using the statc target, `cld-image` component is not rendered (with or without the `responsive` parameter).

**Comment by eyalktCloudinary** [comment] 2021-04-12 09:51
@finex Can you share additional details about the issue? For instance, are you seeing any errors in the console? Can you reproduce the issue in an isolated environment (like https://codesandbox.io/)? Can you share the Cloudinary relevant code snippets (e.g - configuration, `cld-image`)?
