### ISSUE TITLE
Installation/Registration fails

### ISSUE THREAD

**Issue by Sjoerd82** [cloudinary/cloudinary-vue#120] opened 2020-12-05 21:04 UTC
## Describe the bug in a sentence or two.
Error registering plugin

## Issue Type (Can be multiple)
[X] Build - Can’t install or import the SDK
[ ] Babel - Babel errors or cross-browser issues
[ ] UI/Performance - Display or performance issues
[ ] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behavior
[X] Incorrect Types - For typescript users who are having problems with our d.ts files
[ ] Other (Specify)

## Steps to reproduce
run npm install cloudinary-vue and in main.js, use this declaration:
```
import Cloudinary, { CldImage } from 'cloudinary-vue'
Vue.use(Cloudinary, {
    configuration: { cloudName: "REDACTED" },
    components: [ "CldImage" ]
  });
```

On a component I try to use cld-image, like this (but with real values):
`<cld-image cloudName="REDACTED" publicId="1234567890" width="300" crop="scale" />
`I get an error saying the component cld-image does not exist. Which leads me to believe that there is something wrong with the component or registration of it, as seen in screenshot.

I tried `npm install @types/cloudinary-vue`, as suggested by the message, but this fails with a 404: '@types/cloudinary-vue@latest' is not in the npm registry.

On a side note, I got a lot of deprecated package messages on installation.

## Error screenshots
![image](https://user-images.githubusercontent.com/15013786/101262909-2864dc80-3742-11eb-926e-dfb459f5fb64.png)

## Versions and Libraries (fill in the version numbers)
Vue Cloudinary SDK - 1.1.2
Vue - 2.6.10
VueCLI - N/A
Babel - ?
Webpack/Rollup/Other - ?
Node - ?
NPM - 6.11.3

## Config Files (Please paste the following files if possible)
Package.json
{
  "name": "Zephyr",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "serve-production": "npm run build && http-server dist -p 8888"
  },
  "dependencies": {
    "@auth0/auth0-spa-js": "^1.8.1",
    "axios": "^0.19.2",
    "axios-retry": "^3.1.2",
    "cloudinary-vue": "^1.1.2",
    "core-js": "^2.6.5",
    "cuid": "^2.1.8",
    "dexie": "^3.0.1",
    "downloadjs": "^1.4.7",
    "html-to-text": "^5.1.1",
    "jquery": "^3.4.1",
    "lodash": "^4.17.15",
    "lodash-joins": "^3.0.1",
    "material-design-icons-iconfont": "^5.0.1",
    "ngraph.graph": "^19.1.0",
    "ngraph.path": "^1.3.1",
    "pdf-lib": "^1.10.0",
    "register-service-worker": "^1.6.2",
    "streamsaver": "^2.0.4",
    "tiptap": "^1.27.1",
    "tiptap-extensions": "^1.29.1",
    "v-radio-deselectable": "^1.0.3",
    "vue": "^2.6.10",
    "vue-force-next-tick": "^1.1.0",
    "vue-head": "^2.2.0",
    "vue-meta": "^2.3.2",
    "vue-router": "^3.0.3",
    "vue-select": "^3.2.0",
    "vuetify": "^2.3.1"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.11.0",
    "@vue/cli-plugin-eslint": "^3.11.0",
    "@vue/cli-plugin-pwa": "^4.2.3",
    "@vue/cli-service": "^3.11.0",
    "babel-eslint": "^10.0.1",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.0.0",
    "http-server": "^0.12.1",
    "sass": "^1.17.4",
    "sass-loader": "^7.1.0",
    "vue-cli-plugin-vuetify": "^0.6.3",
    "vue-template-compiler": "^2.6.10",
    "vuetify-loader": "^1.4.3"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "rules": {},
    "parserOptions": {
      "parser": "babel-eslint"
    }
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {}
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions"
  ]
}

Webpack.config
Babelrc

## Repository
If possible, please provide a link to a reproducible repository

**Comment by patrick-tolosa** [comment] 2020-12-06 08:44
Hey @Sjoerd82  

I couldn't reproduce this issue, what I tried:

1. Create a new project
2. Copy your package.json
3. Create src/main.js with the code you provided
4. npm install 
5. npm run serve

I did not get any errors at build time.

You mentioned something about a component not existing, but your screenshot is showing a typescript declaration file error.
You also mentioned installing @types/cloudinary-vue, which usually makes sense for typescript projects.

From what you report, it looks like you're having TypeScript issues, but but your build doesn't include typescript.
Could you please try to create a minimal working codebase and share it so we can investigate?

**Comment by Sjoerd82** [comment] 2020-12-09 19:14
Dear Patrick,

Thanks for picking this issue up so quickly. However, while working around the issue I found that it was actually very straightforward to communicate with the Cloudinary API directly from Vue, so I abandoned using this plugin.

If you like you may close this issue. I do Vue/Js/Frameworks mainly as a hobby, so I'm def. not a pro, herein probably lies my issue ;-). For users like me, a simple working example are often great starters.

Kind regards, S.

**Comment by momoip** [comment] 2020-12-10 00:56
Hi Sjoerd82,
Thanks for your response.   I will close this issue.
Best,
Mo

**Comment by mayashavin** [comment] 2020-12-15 09:34
@Sjoerd82 you can check out our playground (including step by step installation and working examples) - https://cloudinary.github.io/cloudinary-vue
Hope it helps.

**Closed by mayashavin** 2020-12-15 09:34 UTC
