### ISSUE TITLE
0: Expected identifier, string or number on Edge

### ISSUE THREAD

**Issue by matthieumarais** [cloudinary/cloudinary-vue#75] opened 2020-05-13 14:12 UTC
Hello team,
I use Cloudinary in my Vuejs web App
version "cloudinary-vue": "^1.0.0"

I have this error only on Edge : 0: Expected identifier, string or number    chunk-vendors.js (777,1)

in my main.js I have this

```
import Cloudinary from 'cloudinary-vue';
Vue.use(Cloudinary, {
    configuration: {
        cloudName: process.env.VUE_APP_CLOUDINARY_CLOUD_NAME
    }
});
```
Have you ever had this problem ?
Thanks for help

**Comment by patrick-tolosa** [comment] 2020-05-14 11:00
Hey @matthieumarais , 
We haven't encountered this issue before,
Is it possible to create a simple reproducible example?

Also, could you please share some more information?
We'd like to know the following versions you're using so we can also test it on our side:

Vue Cloudinary SDK - 0.0.0
Vue - 0.0.0
VueCLI - 0.0.0 / N/A
Babel - 0.0.0
Webpack/Rollup/Other - 0.0.0
Node - 0.0.0
NPM - 0.0.0

Also, we'd love to take a look at the babel config.
Once we have more information and we can reproduce the problem we'll be happy to assist

**Comment by patrick-tolosa** [comment] 2020-06-18 09:49
Hey @matthieumarais 

We were unable to reproduce your issue with the provided information,
I'm closing this issue for now, but if this issue persists please reopen.

**Closed by patrick-tolosa** 2020-06-18 09:49 UTC
