### ISSUE TITLE
Update from beta-2 to 1.0.0 creates issues

### ISSUE THREAD

**Issue by mkbctrl** [cloudinary/cloudinary-vue#60] opened 2020-02-10 13:26 UTC
Hello to all,

I wanted to update the `cloudinary-vue` package from `1.0.0-beta2` to latest version, and once I did it, here's the webpack output:

```
ERROR in ./node_modules/cloudinary-vue/src/index.js
Module parse failed: Unexpected token (10:57)
You may need an appropriate loader to handle this file type.
| const Cloudinary = {
|   install: (Vue, options = {}) => {
|     plugin.install(Vue, options.components ? options : { ...options, components: { CldContext, CldImage, CldVideo, CldTransformation, CldPoster }})
|   }
| };
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./app/javascript/checkout/components/Checkout.vue 54:0-40
 @ ./app/javascript/checkout/components/Checkout.vue
 @ ./app/javascript/checkout/router/index.js
 @ ./app/javascript/packs/checkout_app.js
 @ multi (webpack)-dev-server/client?http://localhost:3035 webpack/hot/dev-server ./app/javascript/packs/checkout_app.js
```

Have anyone encountered simillar issue?

**Comment by idobarnoam** [comment] 2020-02-11 14:18
@mkbctrl Thanks for bringing this to our attention.

We'll take this internally and see share any insights regarding this soon.

**Comment by patrick-tolosa** [comment] 2020-02-11 14:38
Hey @mkbctrl 
I just took a project from beta-2 and upgraded it to 1.0.0 without an issue.

The transpiler is having a problem with here:
`ERROR in ./node_modules/cloudinary-vue/src/index.js`

This shows you're trying to transpile /src/index.js inside the Cloudinary Vue package.
You probably shouldn't consume the /src/ directly, instead, you should  import the package name without a path: `import Cloudinary from 'cloudinary-vue'`
Instead of: `import Cloudinary from 'cloudinary-vue/src/index.js'`

If this doesn't help, can you please share a basic repro or steps to reproduce?

**Comment by mkbctrl** [comment] 2020-02-12 19:16
Hey @patrick-tolosa this is how we import the Cloudinary component,
we do it in the parent/wrapping component of our Checkout process:

```
import Vue from "vue";
  import Cloudinary from 'cloudinary-vue';

  Vue.use(Cloudinary, {
    configuration: {
      cloudName: process.env.CLOUDINARY_VUE_CLOUD,
      secure: true
    }
  });
```

Creating a basic repro will be quiet a task, giving what I have in this project, can't promise it, but I will try to find a solution. 

What were the steps taken to create that issue:
`yarn upgrade cloudinary-vue` and restart of the webpack-dev-server

**Comment by patrick-tolosa** [comment] 2020-02-13 08:41
Thanks @mkbctrl  - That helps identify the problem.

Can you please share your node and npm versions?

**Comment by mkbctrl** [comment] 2020-02-13 10:04
Happy to help:
node: 10.15
npm: 6.4.1

**Comment by patrick-tolosa** [comment] 2020-02-13 22:08
Thanks, I'm trying all sorts of reproduction steps, I can't quite get it to fail as you have.

Could you paste here a few configuration files?

- babelrc
- package.json 

Also if you used VueCLI, what version of VueCLI was used to build this project?

**Comment by mkbctrl** [comment] 2020-02-17 10:23
Here you go:

**babel.rc**
```
{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": "> 1%",
        "uglify": true
      },
      "useBuiltIns": true
    }]
  ],

  "plugins": [
    "syntax-dynamic-import",
    "transform-object-rest-spread",
    ["transform-class-properties", { "spec": true }]
  ]
}

```

**package.json**

```
{
  "engines": {
    "node": "10.15.3"
  },
  "dependencies": {
    "@rails/webpacker": "^3.0.2",
    "@updivision/vue2-multi-uploader": "^1.6.2",
    "axios": "^0.17.1",
    "babel-polyfill": "^6.26.0",
    "bootstrap": "4.0.0-beta.2",
    "chart.js": "^2.7.2",
    "cloudinary-vue": "^1.0.0-beta2",
    "coffeescript": "1.12.7",
    "devour-client": "^2.0.7",
    "i18n-iso-countries": "^3.6.2",
    "intl": "^1.2.5",
    "jquery": "^3.4.1",
    "list.js": "^1.5.0",
    "lodash": "^4.17.5",
    "matchmedia-polyfill": "^0.3.0",
    "mathjs": "^4.4.2",
    "moment": "^2.21.0",
    "normalizr": "^3.2.4",
    "stickyfilljs": "^2.1.0",
    "vee-validate": "^2.0.5",
    "vue": "^2.5.13",
    "vue-axios": "^2.0.2",
    "vue-chartjs": "^3.2.1",
    "vue-flash-message": "^0.6.0",
    "vue-i18n": "^7.4.2",
    "vue-loader": "^13.6.2",
    "vue-router": "^3.0.1",
    "vue-simple-spinner": "^1.2.8",
    "vue-slick": "^1.1.15",
    "vue-table-component": "mwoskowicz/vue-table-component#v1.9.3",
    "vue-template-compiler": "^2.5.13",
    "vue-turbolinks": "^2.0.3",
    "vue-uppy-cloudinary": "mwoskowicz/vue-uppy-cloudinary#v0.0.11",
    "vue2-dropzone": "^3.6.0",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "dotenv": "^6.0.0",
    "webpack-dev-server": "^2.9.5"
  }
}

```

One additional question - don't want to disturb you with yet another issue. Do you have hooks in your package, or are you planning to implement them?

Currently I am using your package for loading the images inside the carousel, that I display on `v-if="true"`. However there is a small UX issue - some of the images takes a little bit longer to load sometimes ( I have them cropped, scaled, etc. ) and I was thinking about using a loader or smth.

Additionaly, one may want to load the images using some lazy loading techniques, with `data-src` attribute in example. It would be also great if you guys can think of such solution as well. 

If you lack man power I think I should be able to find some time to help you - however I am not yet familiar with cloudinary core functions, maybe it's already there.

**Comment by patrick-tolosa** [comment] 2020-02-17 16:05
Thanks,

I've created a basic environment that replicates this issue, 
I think you currently exclude (rightfully so), node_modules from your babel loader.
it probably looks something like this:

` {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
        options: {}
      },`

In my demo environment, I resolved the issue by removing the 'exclude' key (forcing babel to transpile node_modules)

If this is applicable to you, can you please try?

In any case, this is not desired, and we should not point package consumers to our src/index.js which is not transpiled.


Regarding the other things you raised, We would love to continue these discussions, could you please open separate issues so we can discuss further?

**Comment by patrick-tolosa** [comment] 2020-02-20 07:57
Hey @mkbctrl - Any updates on this? 
We'd like to plan for a fix but we just need to confirm this is the root-cause.

**Comment by mkbctrl** [comment] 2020-02-20 12:03
I remember about you, but have to deliver one feature first. I will keep you posted as soon as I have time for it. Sorry to keep you waiting. Hopefully on Monday I should be able to work with it.

**Comment by patrick-tolosa** [comment] 2020-02-20 12:26
Thanks!
No pressure, we're just trying to provide a solution as soon as possible!

**Comment by patrick-tolosa** [comment] 2020-03-18 10:25
@mkbctrl 
Version 1.0.1 was just released that should resolve this issue.

**Comment by patrick-tolosa** [comment] 2020-06-14 08:47
@mkbctrl  - I'm closing this issue due to time passed.
The new version should resolve the issue.

If you still have problems feel free to reopen.

**Closed by patrick-tolosa** 2020-06-14 08:47 UTC
